product-name: minio
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.apply_open_security_group:
    value: false
  .properties.minio_multi_select:
    value:
    - z1
  .properties.minio_number_of_vms:
    value: "1"
  .properties.org:
    value: minio-org
  .properties.space:
    value: minio-space
network-properties:
  network:
    name: default-network
  other_availability_zones:
  - name: z1
  service_network:
    name: default-network
  singleton_availability_zone:
    name: z1
resource-config:
  broker:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
  register-on-demand-service-broker:
    instances: automatic
    instance_type:
      id: automatic
  unregister_on_demand_service_broker:
    instances: automatic
    instance_type:
      id: automatic
  upgrade_all_service_instances:
    instances: automatic
    instance_type:
      id: automatic
errand-config:
  register-on-demand-service-broker:
    post-deploy-state: true
  unregister_on_demand_service_broker:
    pre-delete-state: true
  upgrade_all_service_instances:
    post-deploy-state: true

